### ISSUE TITLE
Update front end container to use /bin/bash not /bin/sh

### ISSUE THREAD

**Issue by thornycrackers** [keeners/techmeet#13]
The docker setup for the Frontend is defaulting to using `/bin/sh` but it would be nicer to just use `bin/bash` instead

**Comment by hyshka** [comment]
Resolved in https://github.com/keeners/techmeet/commit/2c8d1026f5408882fa523d128cc476eba7cc20dd

**Comment by thornycrackers** [comment]
Ty!
