### ISSUE TITLE
Updated frontend container to use docker-compose instead of docker run commands

### ISSUE THREAD

**Issue by thornycrackers** [keeners/techmeet#14]
The makefile for the frontend currentlt uses docker run commands to get the container up and running but we should move it to `docker-compose.yml` like we do for the backend

**Comment by hyshka** [comment]
The frontend container is all hooked into the docker compose setup now. https://github.com/keeners/techmeet/blob/master/docker-compose.yml

**Comment by hyshka** [comment]
Resolved with https://github.com/keeners/techmeet/commit/2c8d1026f5408882fa523d128cc476eba7cc20dd

**Comment by thornycrackers** [comment]
https://github.com/keeners/techmeet/blob/master/techmeet/apps/frontend/Makefile 

can be deleted and  

https://github.com/keeners/techmeet/blob/master/techmeet/apps/frontend/Dockerfile

can be moved into the root level `docker` folder and we can update the root compose.yml's build section to reference the correct file.

**Comment by hyshka** [comment]
@thornycrackers I removed the unused Makefile.

How's this for re-organizing the Dockerfiles? https://github.com/keeners/techmeet/commit/770b7b570609eaef8764f84caef2652653fc031e

**Comment by thornycrackers** [comment]
:ok_hand:
